import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  const APP_TITLE = 'SKILID WEB'
  return (
    <>
      <Head>
        <title>Welcome To Skilid Web Version</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome to Skilid Web</h1>
      </main>
    </>
  )
}
